swagger: '2.0'
tags:
  - name: Text Input Cleansing
get:
  description: Input data yang akan dibersihkan
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error
parameters:
  - name: text
    in: formData
    required: true
    type: string