swagger: '2.0'
tags:
  - name: File Upload Cleansing
get:
  description: Data yang akan dibersihkan
responses:
    '200':
      description: Successful response
    '400':
      description: Bad Request
    '500':
      description: Internal Server Error
parameters:
  - name: file
    in: formData
    type: file
    required: false